#!/bin/sh

#mkdir ~/bin
#export PATH=$PATH:~/bin
#ln -s ~/dotfiles/setup ~/bin

#sudo apt-get update
#sudo apt-get install git-core
#sudo apt-get install tig

# get the basic repos we need
git clone git@github.com:VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
git clone https://github.com/yyuu/pyenv.git ~/.pyenv
git clone git@github.com:puckel/docker-airflow.git ~/docker-tools
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
exec $SHELL
pyenv install 3.6
sudo apt-get install pip
ln -Ls dotfiles/.vim/.vimrc ~/.vimrc
ln -Ls dotfiles/.tmux.conf ~/.tmux.conf
sudo apt-get install unixodbc
sudo apt-get install tdsodbc
# TODO: ODBCINST!!!!
cp ~/dotfiles/templates/tds.driver.template
cp ~/dotfiles/templates/tds.datasource.template
odbcinst -i -d -f tds.driver.template
odbcinst -i -s -f tds.datasource.template
