#!/bin/sh
#sudo apt-get update
#sudo apt-get install git-core

# get the basic repos we need
#git clone git@github.com:VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
#git clone git@github.com:gritlogic/dotfiles.git
#git clone git@github.com:puckel/docker-airflow.git
#git clone https://github.com/yyuu/pyenv.git ~/.pyenv
#echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
#echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
#echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
#exec $SHELL
#pyenv install 3.6
#ln -Ls dotfiles/.vim/.vimrc ~/.vimrc
#ln -Ls dotfiles/.tmux.conf ~/.tmux.conf
#sudo apt-get install unixodbc
#wget "ftp://ftp.freetds.org/pub/freetds/stable/freetds-patched.tar.gz"
# TODO: ODBCINST!!!!

